### PR TITLE
Fix CS in bin/

### PR DESCRIPTION
**Pull request by szepeviktor**
Only 1 left: A PHP file should not be executable; found file permissions set to 0755

### CODE REVIEW

**Comment by leonstafford** [comment]
Thanks! Like the improved ternary. I was kind of leaving those issues in so I'd know when my phpcs runner worked. 

Will resist the .php symlink longer :)

I re-re-read the issue you linked and then noticed the suggestion to use 4.0 dev branch of phpcs, so stopping to beat my head trying to get Filter class working and will try that with fork of your psr-12-neutron-hybrid

**Comment by szepeviktor** [comment]
Please consider not using temporary variables.
`exit((new Auditor($argv[1] ?? __DIR__ . '/..'))->runAudit());`

**Comment by leonstafford** [comment]
Thanks! 

I will bring these changes in. Still fiddling with a way to get me that 4.0 branch into action tonight (fork phpcs, reset `master` to `4.0` is current attack plan)

**Comment by leonstafford** [comment]
Thanks again, applied in https://github.com/leonstafford/WhatWouldViktorDo/commit/d05f82b792aed790d543ec9f54a1fd0e810b6bc0

Is there a sniff/auto-process to fail those temporary vars?

**Comment by szepeviktor** [comment]
> Is there a sniff/auto-process to fail those temporary vars?

I think Slevomat has one.

**Comment by szepeviktor** [comment]
`SlevomatCodingStandard.Variables.UselessVariable` ???

**Pull request closed without merging**
